# Generated by Django 4.1.8 on 2023-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token_author_token_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='likes_count',
            field=models.FloatField(default=0),
        ),
    ]
