# Generated by Django 4.1.8 on 2023-04-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_token_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.token'),
        ),
    ]
