# Generated by Django 4.1.8 on 2023-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_wallet_transaction_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction_history',
            field=models.TextField(default='[]'),
        ),
    ]
