# Generated by Django 4.1.8 on 2023-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_wallet_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='razor_pay_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
