# Generated by Django 4.1.8 on 2023-05-10 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_banner_heading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_alter_wallet_transaction_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('highest_price', models.FloatField()),
                ('brand', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('timeout', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_token_author', to=settings.AUTH_USER_MODEL)),
                ('bidded_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
