# Generated by Django 4.1.8 on 2023-05-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_bidtoken_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtoken',
            name='timeout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
