# Generated by Django 4.1.8 on 2023-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
