# Generated by Django 4.1.8 on 2023-04-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
