# Generated by Django 4.1.8 on 2023-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_remove_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='News Titles', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='news.png', null=True, upload_to='news')),
            ],
        ),
    ]
