# Generated by Django 4.1.8 on 2023-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_banner_options_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='heading',
            field=models.CharField(default='Banner Titles', max_length=200, null=True),
        ),
    ]
