# Generated by Django 4.1.8 on 2023-04-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profiles'),
        ),
    ]
