# Generated by Django 4.1.8 on 2023-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
