# Generated by Django 4.1.8 on 2023-04-24 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wallet'),
        ('accounts', '0007_account_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.wallet'),
        ),
    ]
