# Generated by Django 4.1.8 on 2023-04-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
    ]
