from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('items/',views.items, name='items'),
    path('token-bidding/',views.token_bidding, name='token_bidding'),
    path('categories/',views.categories, name='categories'),
    path('categories/<str:category>/', views.categories, name='categories'),
    path('notice/',views.notice, name='notice'),
    path('profile/',views.profile, name='profile'),
    path('edit-profile/',views.edit_profile, name='edit_profile'),
    path('profile-created/',views.profile_created, name='profile_created'),
    path('wallet/', views.wallet, name='wallet'),
    path('add_funds/', views.add_funds, name='add_funds'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('wallet/redeem/', views.redeem, name='redeem'),
    path('remove-profile/<int:user_id>',views.remove_profile, name='remove_profile'),
    path('cart/',views.cart, name='cart'),
    path('addtocart/<int:id>',views.addtocart, name='addtocart'),
    path('remove-item/<int:id>', views.remove_item, name="remove_item"),
    path('sell/<int:id>', views.sell, name='sell'),
    path('cancel-sale/<int:id>', views.cancel_sale, name='cancel_sale'),
    path('edit-token/<int:id>', views.edit_token, name='edit_token'),
    path('checkout/',views.checkout, name='checkout'),
    path('checkout-single/<int:id>',views.checkout_single, name='checkout_single'),
    path('create/',views.create, name='create'),
    path('single-item/<int:id>', views.single_item, name='single_item'),
    path('like/<int:id>',views.like, name='like'),
    path('dislike/<int:id>',views.dislike, name='dislike'),
    path('base/',views.base, name='base'),
    path('complete_transaction/<int:id>',views.complete_transaction, name='complete_transaction'),
    path('checkout_complete_transaction/',views.checkout_complete_transaction, name='checkout_complete_transaction'),
]
